"""Statistic array encodings: the plan, the codec, and the decoded planes.

ADR 0037 / issue #119. `StoreEncoding` is decided once at build time from
measured properties of the data and recorded in `manifest.json`; `StoreCodec`
is the only place a store's stored bytes become physical values.
"""

from opengwasdb.encoding.codec import (
    EAF_BASELINE,
    EAF_EXCEPTION_INDEX,
    EAF_EXCEPTION_VALUE,
    EAF_REFERENCE,
    Z_OVERFLOW_INDEX,
    Z_OVERFLOW_VALUE,
    EafExceptionBuilder,
    EafExceptionTable,
    SparseExactBuilder,
    SparseExactTable,
    StoreCodec,
    ZOverflowBuilder,
    ZOverflowTable,
    eaf_baseline_from_grid,
    eaf_baseline_from_pairs,
    expit,
    logit,
    positions_at,
    positions_flat,
    positions_pairs,
    positions_row_band,
    positions_rows_cols,
)
from opengwasdb.encoding.measure import (
    combine_eaf_measurements,
    measure_eaf,
    measure_eaf_grid,
    measure_eaf_sample,
)
from opengwasdb.encoding.plan import (
    DEFAULT_Z_SCALE,
    EAF_ABSENT,
    EAF_CODE_MAX,
    EAF_CODE_MIN,
    EAF_EXCEPTION,
    EAF_EXCEPTION_BUDGET,
    EAF_RANGE_CANDIDATES,
    ENCODING_VERSION,
    Z_MISSING,
    Z_OVERFLOW,
    EafBaselineError,
    EafEncoding,
    EafMeasurements,
    EncodingMeasurements,
    SeEncoding,
    StoreEncoding,
    UnsupportedEncoding,
    ZEncoding,
)
from opengwasdb.encoding.planes import (
    DEFAULT_PER_VARIANT_CHUNK,
    DenseEafPlane,
    DenseZPlane,
    RaggedEafPlane,
    per_variant_chunk_size,
    write_eaf_baseline,
    write_eaf_csr,
    write_eaf_reference,
)

__all__ = [
    "DEFAULT_PER_VARIANT_CHUNK",
    "DEFAULT_Z_SCALE",
    "ENCODING_VERSION",
    "DenseEafPlane",
    "DenseZPlane",
    "EAF_ABSENT",
    "EAF_BASELINE",
    "EAF_CODE_MAX",
    "EAF_CODE_MIN",
    "EAF_EXCEPTION",
    "EAF_EXCEPTION_BUDGET",
    "EAF_EXCEPTION_INDEX",
    "EAF_EXCEPTION_VALUE",
    "EAF_RANGE_CANDIDATES",
    "EAF_REFERENCE",
    "EafBaselineError",
    "EafEncoding",
    "EafExceptionBuilder",
    "EafExceptionTable",
    "EafMeasurements",
    "EncodingMeasurements",
    "RaggedEafPlane",
    "SeEncoding",
    "SparseExactBuilder",
    "SparseExactTable",
    "StoreCodec",
    "StoreEncoding",
    "UnsupportedEncoding",
    "ZEncoding",
    "ZOverflowBuilder",
    "ZOverflowTable",
    "Z_MISSING",
    "combine_eaf_measurements",
    "Z_OVERFLOW",
    "Z_OVERFLOW_INDEX",
    "Z_OVERFLOW_VALUE",
    "eaf_baseline_from_grid",
    "eaf_baseline_from_pairs",
    "expit",
    "logit",
    "measure_eaf",
    "measure_eaf_grid",
    "measure_eaf_sample",
    "positions_at",
    "positions_flat",
    "positions_pairs",
    "positions_row_band",
    "positions_rows_cols",
    "per_variant_chunk_size",
    "write_eaf_baseline",
    "write_eaf_csr",
    "write_eaf_reference",
]
