#!/usr/bin/env python3
"""Generate (or splice) ADR 0058's "Checked on FinnGen (#250)" block.

Every number is read from the committed #250 artifacts, so the ADR section is
never retyped:

* `docs/benchmark-output/opengwasdb_ogs00016_store_comparison_zarr3.json`
  (the 0.1.0 vs 0.2.0 timings, and the per-plane footprint),
* `docs/benchmark-output/opengwasdb_ogs00016_conversion_0_2_0.json`
  (the total size change and file counts).

Usage, from the repository root::

    python3 scripts/build_finngen_shape_check.py            # print the block
    python3 scripts/build_finngen_shape_check.py --write    # splice it into ADR 0058

`--write` replaces everything between the markers

    <!-- BEGIN GENERATED: finngen-shape-check (#250) -->
    <!-- END GENERATED: finngen-shape-check (#250) -->

so the committed ADR text is exactly this output. `--check` exits non-zero when
the ADR no longer matches the artifacts.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

OUT = Path("docs/benchmark-output")
ADR = Path("docs/adr/0058-dense-chunk-and-shard-shapes.md")
BEGIN = "<!-- BEGIN GENERATED: finngen-shape-check (#250) -->"
END = "<!-- END GENERATED: finngen-shape-check (#250) -->"

#: ADR 0058's own OGS-00009 ratios (0.1.0 -> 0.2.0 under Zarr 3), quoted from
#: the ADR for comparison; the FinnGen ratios beside them are computed here.
OGS00009_RATIOS = {
    "phewas": 2.76,
    "random_lookup_10_variants_100_analyses": 2.80,
    "random_lookup_100_variants_10_analyses": 1.83,
    "regional": 1.35,
    "bulk": 0.35,
}
PLANES = (
    "data.zarr/z",
    "data.zarr/se",
    "data.zarr/eaf",
    "data.zarr/top_hits/p_5e_04/z",
)


def build() -> str:
    import json

    cmp_path = OUT / "opengwasdb_ogs00016_store_comparison_zarr3.json"
    conv_path = OUT / "opengwasdb_ogs00016_conversion_0_2_0.json"
    cmp = json.loads(cmp_path.read_text())
    conv = json.loads(conv_path.read_text())
    stores = {store["label"]: store for store in cmp["stores"]}
    dataset = stores["v2-ogs00016"]["dataset"]
    v2 = {row["query"]: row for row in stores["v2-ogs00016"]["timings"]}
    v3 = {row["query"]: row for row in stores["v3-ogs00016"]["timings"]}
    arrays2 = {a["node"]: a for a in stores["v2-ogs00016"]["footprint"]["arrays"]}
    arrays3 = {a["node"]: a for a in stores["v3-ogs00016"]["footprint"]["arrays"]}
    total = conv["after"]["apparent_bytes"] / conv["before"]["apparent_bytes"] * 100 - 100

    lines = [
        "## Checked on FinnGen (#250)",
        "",
        "Generated by `python3 scripts/build_finngen_shape_check.py` from "
        f"`docs/benchmark-output/{cmp_path.name}` and "
        f"`docs/benchmark-output/{conv_path.name}`. Run on the full FinnGen R13 release "
        f"({dataset['n_analyses']:,} Analyses x {dataset['n_variants']:,} variants), "
        "converted bit-exactly from 0.1.0 to 0.2.0. "
        f"Total apparent size grows **{total:+.2f} %** ({conv['before']['n_files']:,} files -> "
        f"**{conv['after']['n_files']:,}**). The only material per-plane cost is the `se` plane; "
        "`z` and the top-hit index are flat:",
        "",
        "| array | 0.1.0 | 0.2.0 | ratio |",
        "|---|---:|---:|---:|",
    ]
    for node in PLANES:
        a, b = arrays2[node]["apparent_bytes"], arrays3[node]["apparent_bytes"]
        lines.append(
            f"| `{node.removeprefix('data.zarr/')}` | {a / 1e9:.2f} GB | {b / 1e9:.2f} GB | "
            f"{b / a:.3f}x |"
        )
    lines += [
        "",
        "The 0.1.0 -> 0.2.0 time ratios under Zarr 3 match this ADR's OGS-00009 ratios:",
        "",
        "| shape | FinnGen | OGS-00009 (this ADR) |",
        "|---|---:|---:|",
    ]
    for shape, reference in OGS00009_RATIOS.items():
        lines.append(
            f"| {shape.replace('_', ' ')} | {v3[shape]['median_ms'] / v2[shape]['median_ms']:.2f}x "
            f"| {reference:.2f}x |"
        )
    lines += [
        "",
        f"No new size or time cost appears, and the whole-Analysis guard holds "
        f"({v3['bulk']['median_ms'] / v2['bulk']['median_ms']:.2f}x against the 1.25x limit). "
        "**The decision is not contradicted and is not corrected.** Full report: "
        "`docs/benchmark-output/opengwasdb_ogs00016_0_2_0.html`.",
        "",
    ]
    return "\n".join(lines)


def splice(block: str, *, write: bool) -> int:
    text = ADR.read_text()
    before, _, rest = text.partition(BEGIN)
    _, _, after = rest.partition(END)
    if not (before and rest and after):
        raise SystemExit(f"{ADR}: missing the generated-block markers")
    replacement = f"{BEGIN}\n{block}{END}"
    updated = before + replacement + after
    if write:
        ADR.write_text(updated)
        print(f"{ADR}: spliced {len(block)} characters")
        return 0
    if updated != text:
        print(f"{ADR}: the committed block differs from the artifacts", file=sys.stderr)
        return 1
    print(f"{ADR}: matches the artifacts")
    return 0


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--write", action="store_true", help="splice the block into ADR 0058")
    ap.add_argument("--check", action="store_true", help="fail if ADR 0058 is out of date")
    args = ap.parse_args()
    block = build()
    if args.write or args.check:
        raise SystemExit(splice(block, write=args.write))
    print(block)


if __name__ == "__main__":
    main()
